name: mathematical.coffee
# write author: amy on your posts to have it signed.
authors: 
    amy:
        display_name: mathematical.coffee
        email: mathematical.coffee@gmail.com
        gravatar: b5ea0d229d6133caa156292bbe25095f 
        bio: Mathematician by training, coder by hobby, <a href="http://www.nethack.org">nethacker</a> for life! I also enjoy making silly little crochet toys.
        twitter: mathematicoffee
        googleplus: AmycoffeebugChan
        github: mathematicalcoffee
        bitbucket: mathematicalcoffee
        web: http://mathematicalcoffee.github.com
        # facebook: pages/PageName  or your username (appended to facebook.com/)
description: Demonstrating a skeleton build for a blog.
timezone: "Australia/Brisbane"
# the twitter for the site (as opposed to indiv. authors)
twitter: mathematicoffee

pagination: 5

markdown: kramdown
kramdown:
    input: GFM
pygments: true

social:
    twitter: mathematicoffee
    googleplus: AmycoffeebugChan
    github: mathematicalcoffee
    bitbucket: mathematicalcoffee
social-post: [twitter, facebook, googleplus, pinterest]
social-aboutme: [twitter, facebook, googleplus, github, bitbucket, flickr]
