name: mathematical.coffee
# write author: amy on your posts to have it signed.
url: http://mathematicalcoffee.github.com
authors: 
    # author:
    #   # for all authors, required:
    #     display_name: the name as you wish to display it
    #     # this is necessary for now as jekyll does not support handlelize filter
    #     handle: the name run through `handleize`: downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
    #   # recommended:
    #     email: email address
    #     gravatar: your gravatar hash (md5 of your email address)
    #     bio: a quick bio
    #   # optional:
    #     bitbucket:
    #     facebook:
    #     flickr:
    #     github:
    #     googleplus:
    #     pinterest:
    #     twitter:
    #     web:
    amy:
        display_name: mathematical.coffee
        handle: mathematicalcoffee
        email: mathematical.coffee@gmail.com
        gravatar: b5ea0d229d6133caa156292bbe25095f 
        bio: Mathematician by training, coder by hobby, <a href="http://www.nethack.org">nethacker</a> for life! I also enjoy making silly little crochet toys.
        twitter: mathematicoffee
        googleplus: AmycoffeebugChan
        github: mathematicalcoffee
        bitbucket: mathematicalcoffee
        web: http://mathematicalcoffee.github.com
    john:
        display_name: John Smith
        handle: john-smith
        email: john.smith@email.com
        gravatar: 12345
        bio: Your modern mystery man.
        # see _data/social.yml.
        # bitbucket, email, facebook, flickr, github, googleplus, pinterest, twitter
        twitter: twitter
        # not yet used
        # web: http://johndoe.com
description: Demonstrating a skeleton build for a blog.

# ------ SITE CONFIGURATION ------ #
social: # site accounts as opposed to author accounts (only twitter used for 'share via')
    twitter: mathematicoffee

# for each post, what social share widgets do you want? (see _data/social.yml, needs
# 'share' entry)
social-post: [twitter, facebook, googleplus, pinterest]

# search results
search:
    # display listing of titles only, or excerpts?
    titles-only: false

# What to put into the right-hand sidebar.
sidebar:
    # available widgets: about, archive, cloud
    # they appear in the order you list.
    widgets: [archive, about, cloud]
    # --- configuration of widgets ---
    # about me sidebar widget configuration
    about:
        # for each author, what shall we show on the social bar (in this order)?
        # choose from _social/data.yml (and add the nickname into authors)
        social: [email, twitter, facebook, googleplus, github, bitbucket, flickr]
    # archive sidebar widget configuration
    archive:
        # has no options.
    # cloud sidebar widget configuration.
    cloud:
        # what to make clouds of and in what order? tags, categories.
        what: [tags, categories]
        # minimum font size for tags? Note: it is attained.
        minfontsize: 13
        # maximum font size for tags? basically tweak-and-see
        # it will never quite be reached.
        maxfontsize: 30

# ------ JEKYLL CONFIGURATION ------ #
pagination: 5

markdown: kramdown
kramdown:
    input: GFM
pygments: true
relative_permalinks: false
permalink: /:year/:month/:day/:title

timezone: "Australia/Brisbane"

exclude: [Rakefile, Gemfile, Gemfile.lock, README.md]
