name: My Blog
# blog subtitle
description: Demonstrating a skeleton build for a blog.
url: http://your.url.com
timezone: "Australia/Brisbane"
authors: 
    # on posts, can put "authors: [jane, john]"
    # author:
    #   # for all authors, required:
    #     display_name: the name as you wish to display it
    #     handle: necessary since jekyll-github seems not to support the handleize filter.
    #             Use `rake handleize['John Smith']` to get it.
    #   # recommended:
    #     email: email address
    #     gravatar: your gravatar hash (md5 of your email address)
    #     bio: a quick bio
    #   # optional:
    #     bitbucket:
    #     facebook:
    #     flickr:
    #     github:
    #     googleplus:
    #     pinterest:
    #     twitter:
    #     web:
    john:
        display_name: John Smith
        handle: john-smith
        email: john.smith@email.com
        gravatar: 12345
        bio: Your modern mystery man.
        # see _data/social.yml.
        # bitbucket, email, facebook, flickr, github, googleplus, pinterest, twitter
        twitter: twitter
        # not yet used
        web: http://janesmith.com
    jane:
      display_name: Jane Doe
      handle: jane-doe
      email: ~
      web: ~
      gravatar: 54321
      bio: Your modern mystery woman.
      bitbucket: ~
      facebook: ~
      flickr: ~
      github: ~
      googleplus: ~
      pinterest: ~
      twitter: ~

# ------ SITE CONFIGURATION ------ #
# disqus shortname for the site. if not here you don't get comments.
disqus_shortname: EDITME
social: # site accounts as opposed to author accounts (only twitter used for 'share via')
    twitter: ~

# should we put subscribe links in the header? if so, what?
# Options: anything in site.social (e.g. twitter) and atom, rss.
subscribe-header: [rss, atom, twitter]

# for each post, what social share widgets do you want? (see _data/social.yml, needs
# 'share' entry)
social-post: [twitter, facebook, googleplus, pinterest]

# What to put into the right-hand sidebar.
sidebar:
    # available widgets: about, archive, cloud, subscribe
    # they appear in the order you list.
    widgets: [archive, about, cloud, subscribe]
    # --- configuration of widgets ---
    # about me sidebar widget configuration
    about:
        # for each author, what shall we show on the social bar (in this order)?
        # choose from _social/data.yml (and add the nickname into authors)
        social: [email, twitter, facebook, googleplus, github, bitbucket, flickr]
    # archive sidebar widget configuration
    archive:
        # has no options.
    # cloud sidebar widget configuration.
    cloud:
        # what to make clouds of and in what order? tags, categories.
        what: [tags, categories]
        # minimum font size for tags? Note: it is attained.
        minfontsize: 13
        # maximum font size for tags? basically tweak-and-see
        # it will never quite be reached.
        maxfontsize: 30
        # maximum number of tags/categories to display (good if you have heaps)
        maxtags: 10
    # subscribe links. what to list. Options:
    # - anything in site.social (e.g. twitter)
    # - rss and atom
    subscribe: [rss, atom, twitter]

# ------ JEKYLL CONFIGURATION ------ #
pagination: 5

markdown: redcarpet
redcarpet:
    extensions: [no_intra_emphasis, tables, lax_spacing, with_toc_data]
highlighter: pygments
relative_permalinks: false
permalink: /:year/:month/:day/:title


exclude: [Rakefile, Gemfile, Gemfile.lock, README.md]
