name: mathematical.coffee
description: Demonstrating a skeleton build for a blog.
timezone: "Australia/Brisbane"
twitter: "@mathematicoffee"

pagination: 5

markdown: kramdown
kramdown:
    input: GFM
pygments: true

social:
    twitter: mathematicoffee
    googleplus: AmycoffeebugChan
    github: mathematicalcoffee
    bitbucket: mathematicalcoffee
social-post: [twitter, facebook, googleplus, pinterest]
