name: mathematical.coffee
# write author: amy on your posts to have it signed.
authors: 
    amy:
        display_name: mathematical.coffee
        email: mathematical.coffee@gmail.com
        gravatar: b5ea0d229d6133caa156292bbe25095f 
        bio: Mathematician by training, coder by hobby, <a href="http://www.nethack.org">nethacker</a> for life! I also enjoy making silly little crochet toys.
        twitter: mathematicoffee
        googleplus: AmycoffeebugChan
        github: mathematicalcoffee
        bitbucket: mathematicalcoffee
        web: http://mathematicalcoffee.github.com
        # facebook: pages/PageName  or your username (appended to facebook.com/)
description: Demonstrating a skeleton build for a blog.

# ------ SITE CONFIGURATION ------ #
social: # site accounts as opposed to author accounts (only twitter used for 'share via')
    twitter: mathematicoffee

# for each post, what social share widgets do you want? (see _data/social.yml, needs
# 'share' entry)
social-post: [twitter, facebook, googleplus, pinterest]

# What to put into the right-hand sidebar.
sidebar:
    # available widgets: about, archive, cloud
    # they appear in the order you list.
    widgets: [archive, about, cloud]
    # --- configuration of widgets ---
    # aboutme sidebar widget configuration
    aboutme:
        # for each author, what shall we show on the social bar (in this order)?
        # choose from _social/data.yml (and add the nickname into authors)
        social: [email, twitter, facebook, googleplus, github, bitbucket, flickr]
    # archive sidebar widget configuration
    archive:
        # has no options.
    # cloud sidebar widget configuration.
    cloud:
        # what to make clouds of and in what order? tags, categories.
        what: [tags, categories]
        # minimum font size for tags? basically tweak-and-see
        #  (only if no post has this category will the size be attained)
        minfontsize: 5
        # maximum font size for tags? basically tweak-and-see
        #  (only if every post has this category will the size be attained)
        maxfontsize: 30

# ------ JEKYLL CONFIGURATION ------ #
pagination: 5

markdown: kramdown
kramdown:
    input: GFM
pygments: true

timezone: "Australia/Brisbane"
